// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: authors.sql

package dbq

import (
	"context"
	"strings"
)

const authorFirstChars = `-- name: AuthorFirstChars :many
SELECT DISTINCT substr(a.name_fold, 1, 1) AS first_char
FROM authors a
WHERE EXISTS (SELECT 1
              FROM book_authors ba
                       JOIN books b ON b.id = ba.book_id
              WHERE ba.author_id = a.id
                AND (CAST(?1 AS INTEGER) = 0 OR b.library_id = ?1))
`

// AuthorFirstChars returns the distinct first character of every author name
// (library-scoped), feeding the browse page's alphabet selector. The caller
// buckets these into the Cyrillic / Latin / '#' letters it renders. name_fold is
// uppercase, so its first char lands in the uppercase buckets bucketOf expects.
func (q *Queries) AuthorFirstChars(ctx context.Context, libraryID int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, authorFirstChars, libraryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var first_char string
		if err := rows.Scan(&first_char); err != nil {
			return nil, err
		}
		items = append(items, first_char)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteBookAuthors = `-- name: DeleteBookAuthors :exec
DELETE
FROM book_authors
WHERE book_id = ?
`

func (q *Queries) DeleteBookAuthors(ctx context.Context, bookID int64) error {
	_, err := q.db.ExecContext(ctx, deleteBookAuthors, bookID)
	return err
}

const insertAuthor = `-- name: InsertAuthor :one
INSERT INTO authors (name, name_fold)
VALUES (?, ?)
ON CONFLICT (name_fold) DO UPDATE SET name = name
RETURNING id
`

type InsertAuthorParams struct {
	Name     string
	NameFold string
}

// InsertAuthor upserts by name_fold (the uppercase case-fold key), so case
// variants from different records collapse to one row. The existing display
// name is kept (first writer wins); DO UPDATE is only there so RETURNING yields
// the id on conflict.
func (q *Queries) InsertAuthor(ctx context.Context, arg InsertAuthorParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertAuthor, arg.Name, arg.NameFold)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertBookAuthor = `-- name: InsertBookAuthor :exec
INSERT INTO book_authors (book_id, author_id)
VALUES (?, ?)
ON CONFLICT DO NOTHING
`

type InsertBookAuthorParams struct {
	BookID   int64
	AuthorID int64
}

func (q *Queries) InsertBookAuthor(ctx context.Context, arg InsertBookAuthorParams) error {
	_, err := q.db.ExecContext(ctx, insertBookAuthor, arg.BookID, arg.AuthorID)
	return err
}

const listAuthors = `-- name: ListAuthors :many
SELECT a.id, a.name, a.name_fold, COUNT(b.id) AS book_count
FROM authors a
         JOIN book_authors ba ON ba.author_id = a.id
         JOIN books b ON b.id = ba.book_id
WHERE (CAST(?1 AS INTEGER) = 0 OR b.library_id = ?1)
GROUP BY a.id
ORDER BY a.name_fold
LIMIT ?3 OFFSET ?2
`

type ListAuthorsParams struct {
	LibraryID int64
	Off       int64
	Lim       int64
}

type ListAuthorsRow struct {
	ID        int64
	Name      string
	NameFold  string
	BookCount int64
}

// ListAuthors lists every author (library-scoped), paginated. OPDS index feeds
// page through it with @lim/@off; pass a large @lim with @off 0 for "all".
func (q *Queries) ListAuthors(ctx context.Context, arg ListAuthorsParams) ([]ListAuthorsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAuthors, arg.LibraryID, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAuthorsRow
	for rows.Next() {
		var i ListAuthorsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.NameFold,
			&i.BookCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuthorsByLetter = `-- name: ListAuthorsByLetter :many
SELECT a.id,
       a.name,
       (SELECT COUNT(*)
        FROM book_authors ba
        WHERE ba.author_id = a.id
          AND (CAST(?1 AS INTEGER) = 0
            OR EXISTS (SELECT 1 FROM books b WHERE b.id = ba.book_id AND b.library_id = ?1))) AS book_count
FROM authors a
WHERE a.name_fold >= ?2
  AND a.name_fold < ?3
  AND EXISTS (SELECT 1
              FROM book_authors ba2
                       JOIN books b ON b.id = ba2.book_id
              WHERE ba2.author_id = a.id
                AND (CAST(?1 AS INTEGER) = 0 OR b.library_id = ?1))
ORDER BY a.name_fold
LIMIT ?5 OFFSET ?4
`

type ListAuthorsByLetterParams struct {
	LibraryID int64
	Lo        string
	Hi        string
	Off       int64
	Lim       int64
}

type ListAuthorsByLetterRow struct {
	ID        int64
	Name      string
	BookCount int64
}

// ListAuthorsByLetter lists one alphabet bucket, paginated. It seeks the
// authors.name_fold index with the [@lo, @hi) range the caller computes for the
// selected letter, so it stays fast even for late letters in a huge library.
func (q *Queries) ListAuthorsByLetter(ctx context.Context, arg ListAuthorsByLetterParams) ([]ListAuthorsByLetterRow, error) {
	rows, err := q.db.QueryContext(ctx, listAuthorsByLetter,
		arg.LibraryID,
		arg.Lo,
		arg.Hi,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAuthorsByLetterRow
	for rows.Next() {
		var i ListAuthorsByLetterRow
		if err := rows.Scan(&i.ID, &i.Name, &i.BookCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuthorsForBook = `-- name: ListAuthorsForBook :many
SELECT a.id, a.name, a.name_fold
FROM authors a
         JOIN book_authors ba ON ba.author_id = a.id
WHERE ba.book_id = ?
ORDER BY a.name_fold
`

func (q *Queries) ListAuthorsForBook(ctx context.Context, bookID int64) ([]Author, error) {
	rows, err := q.db.QueryContext(ctx, listAuthorsForBook, bookID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Author
	for rows.Next() {
		var i Author
		if err := rows.Scan(&i.ID, &i.Name, &i.NameFold); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuthorsForBooks = `-- name: ListAuthorsForBooks :many
SELECT ba.book_id, a.id, a.name
FROM authors a
         JOIN book_authors ba ON ba.author_id = a.id
WHERE ba.book_id IN (/*SLICE:book_ids*/?)
ORDER BY ba.book_id, a.name_fold
`

type ListAuthorsForBooksRow struct {
	BookID int64
	ID     int64
	Name   string
}

// ListAuthorsForBooks returns the author links for a whole page of books in
// one statement (instead of one ListAuthorsForBook per book), keyed by book_id.
func (q *Queries) ListAuthorsForBooks(ctx context.Context, bookIds []int64) ([]ListAuthorsForBooksRow, error) {
	query := listAuthorsForBooks
	var queryParams []interface{}
	if len(bookIds) > 0 {
		for _, v := range bookIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:book_ids*/?", strings.Repeat(",?", len(bookIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:book_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAuthorsForBooksRow
	for rows.Next() {
		var i ListAuthorsForBooksRow
		if err := rows.Scan(&i.BookID, &i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuthorsNonLetter = `-- name: ListAuthorsNonLetter :many
SELECT a.id,
       a.name,
       (SELECT COUNT(*)
        FROM book_authors ba
        WHERE ba.author_id = a.id
          AND (CAST(?1 AS INTEGER) = 0
            OR EXISTS (SELECT 1 FROM books b WHERE b.id = ba.book_id AND b.library_id = ?1))) AS book_count
FROM authors a
WHERE NOT ((a.name_fold >= char(1040) AND a.name_fold < char(1072)) OR
           (a.name_fold >= char(65) AND a.name_fold < char(91)))
  AND EXISTS (SELECT 1
              FROM book_authors ba2
                       JOIN books b ON b.id = ba2.book_id
              WHERE ba2.author_id = a.id
                AND (CAST(?1 AS INTEGER) = 0 OR b.library_id = ?1))
ORDER BY a.name_fold
LIMIT ?3 OFFSET ?2
`

type ListAuthorsNonLetterParams struct {
	LibraryID int64
	Off       int64
	Lim       int64
}

type ListAuthorsNonLetterRow struct {
	ID        int64
	Name      string
	BookCount int64
}

// ListAuthorsNonLetter is the '#' bucket: authors whose name starts outside the
// Cyrillic (char 1040..1071) and Latin A-Z (char 65..90) ranges: digits,
// punctuation, lowercase, and other scripts. See bucketOf in letters.go.
func (q *Queries) ListAuthorsNonLetter(ctx context.Context, arg ListAuthorsNonLetterParams) ([]ListAuthorsNonLetterRow, error) {
	rows, err := q.db.QueryContext(ctx, listAuthorsNonLetter, arg.LibraryID, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAuthorsNonLetterRow
	for rows.Next() {
		var i ListAuthorsNonLetterRow
		if err := rows.Scan(&i.ID, &i.Name, &i.BookCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
