// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: books.sql

package dbq

import (
	"context"
	"database/sql"
	"strings"
)

const countBooksByLibrary = `-- name: CountBooksByLibrary :one
SELECT COUNT(*)
FROM books
WHERE library_id = ?
`

func (q *Queries) CountBooksByLibrary(ctx context.Context, libraryID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countBooksByLibrary, libraryID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteBook = `-- name: DeleteBook :exec
DELETE
FROM books
WHERE id = ?
`

func (q *Queries) DeleteBook(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteBook, id)
	return err
}

const deleteBookFile = `-- name: DeleteBookFile :exec
DELETE
FROM book_files
WHERE id = ?
`

func (q *Queries) DeleteBookFile(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteBookFile, id)
	return err
}

const deleteBooksByLibrary = `-- name: DeleteBooksByLibrary :exec
DELETE
FROM books
WHERE library_id = ?
`

func (q *Queries) DeleteBooksByLibrary(ctx context.Context, libraryID int64) error {
	_, err := q.db.ExecContext(ctx, deleteBooksByLibrary, libraryID)
	return err
}

const findBookByLibraryKey = `-- name: FindBookByLibraryKey :one
SELECT b.id, b.library_id, b.library_key, b.title, b.series_id, b.series_number, b.language, b.annotation, b.metadata_checked, b.enrichment_checked, b.publisher, b.publisher_fold, b.year, b.rating, b.content_hash, b.metadata_format, b.added_at, b.imported_at, b.manually_matched, b.cover_prio, COALESCE(s.name, '') AS series_name
FROM books b
         LEFT JOIN series s ON s.id = b.series_id
WHERE b.library_id = ?
  AND b.library_key = ?
`

type FindBookByLibraryKeyParams struct {
	LibraryID  int64
	LibraryKey string
}

type FindBookByLibraryKeyRow struct {
	ID                int64
	LibraryID         int64
	LibraryKey        string
	Title             string
	SeriesID          sql.NullInt64
	SeriesNumber      sql.NullFloat64
	Language          string
	Annotation        sql.NullString
	MetadataChecked   int64
	EnrichmentChecked int64
	Publisher         sql.NullString
	PublisherFold     sql.NullString
	Year              sql.NullInt64
	Rating            sql.NullInt64
	ContentHash       string
	MetadataFormat    sql.NullString
	AddedAt           int64
	ImportedAt        int64
	ManuallyMatched   int64
	CoverPrio         int64
	SeriesName        string
}

func (q *Queries) FindBookByLibraryKey(ctx context.Context, arg FindBookByLibraryKeyParams) (FindBookByLibraryKeyRow, error) {
	row := q.db.QueryRowContext(ctx, findBookByLibraryKey, arg.LibraryID, arg.LibraryKey)
	var i FindBookByLibraryKeyRow
	err := row.Scan(
		&i.ID,
		&i.LibraryID,
		&i.LibraryKey,
		&i.Title,
		&i.SeriesID,
		&i.SeriesNumber,
		&i.Language,
		&i.Annotation,
		&i.MetadataChecked,
		&i.EnrichmentChecked,
		&i.Publisher,
		&i.PublisherFold,
		&i.Year,
		&i.Rating,
		&i.ContentHash,
		&i.MetadataFormat,
		&i.AddedAt,
		&i.ImportedAt,
		&i.ManuallyMatched,
		&i.CoverPrio,
		&i.SeriesName,
	)
	return i, err
}

const getBook = `-- name: GetBook :one
SELECT id, library_id, library_key, title, series_id, series_number, language, annotation, metadata_checked, enrichment_checked, publisher, publisher_fold, year, rating, content_hash, metadata_format, added_at, imported_at, manually_matched, cover_prio
FROM books
WHERE id = ?
`

func (q *Queries) GetBook(ctx context.Context, id int64) (Book, error) {
	row := q.db.QueryRowContext(ctx, getBook, id)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.LibraryID,
		&i.LibraryKey,
		&i.Title,
		&i.SeriesID,
		&i.SeriesNumber,
		&i.Language,
		&i.Annotation,
		&i.MetadataChecked,
		&i.EnrichmentChecked,
		&i.Publisher,
		&i.PublisherFold,
		&i.Year,
		&i.Rating,
		&i.ContentHash,
		&i.MetadataFormat,
		&i.AddedAt,
		&i.ImportedAt,
		&i.ManuallyMatched,
		&i.CoverPrio,
	)
	return i, err
}

const getBookFile = `-- name: GetBookFile :one
SELECT id, book_id, file_format, file_size, source_path, pages, mtime
FROM book_files
WHERE id = ?
`

func (q *Queries) GetBookFile(ctx context.Context, id int64) (BookFile, error) {
	row := q.db.QueryRowContext(ctx, getBookFile, id)
	var i BookFile
	err := row.Scan(
		&i.ID,
		&i.BookID,
		&i.FileFormat,
		&i.FileSize,
		&i.SourcePath,
		&i.Pages,
		&i.Mtime,
	)
	return i, err
}

const globalBooksByFormat = `-- name: GlobalBooksByFormat :many
SELECT file_format, COUNT(DISTINCT book_id) AS book_count
FROM book_files
GROUP BY file_format
ORDER BY book_count DESC
`

type GlobalBooksByFormatRow struct {
	FileFormat string
	BookCount  int64
}

func (q *Queries) GlobalBooksByFormat(ctx context.Context) ([]GlobalBooksByFormatRow, error) {
	rows, err := q.db.QueryContext(ctx, globalBooksByFormat)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GlobalBooksByFormatRow
	for rows.Next() {
		var i GlobalBooksByFormatRow
		if err := rows.Scan(&i.FileFormat, &i.BookCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const globalBooksByLanguage = `-- name: GlobalBooksByLanguage :many
SELECT language, COUNT(*) AS book_count
FROM books
GROUP BY language
ORDER BY book_count DESC
`

type GlobalBooksByLanguageRow struct {
	Language  string
	BookCount int64
}

func (q *Queries) GlobalBooksByLanguage(ctx context.Context) ([]GlobalBooksByLanguageRow, error) {
	rows, err := q.db.QueryContext(ctx, globalBooksByLanguage)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GlobalBooksByLanguageRow
	for rows.Next() {
		var i GlobalBooksByLanguageRow
		if err := rows.Scan(&i.Language, &i.BookCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const globalStats = `-- name: GlobalStats :one
SELECT (SELECT COUNT(*) FROM books)                                          AS total_books,
       (SELECT CAST(COALESCE(SUM(file_size), 0) AS INTEGER) FROM book_files) AS total_size_bytes,
       (SELECT COUNT(DISTINCT author_id) FROM book_authors)                  AS authors,
       (SELECT COUNT(DISTINCT series_id) FROM books)                         AS series,
       (SELECT COUNT(*) FROM libraries)                                      AS libraries
`

type GlobalStatsRow struct {
	TotalBooks     int64
	TotalSizeBytes int64
	Authors        int64
	Series         int64
	Libraries      int64
}

// GlobalStats returns catalog totals in one query. The authors/series counts use
// COUNT(DISTINCT child_fk) rather than a correlated EXISTS over the parent table:
// book_authors.author_id and books.series_id are FK-backed (ON DELETE CASCADE /
// SET NULL), so a parent row is referenced iff it appears here. This counts only
// non-orphan parents while scanning the child tables (index-assisted) instead of
// every parent row.
func (q *Queries) GlobalStats(ctx context.Context) (GlobalStatsRow, error) {
	row := q.db.QueryRowContext(ctx, globalStats)
	var i GlobalStatsRow
	err := row.Scan(
		&i.TotalBooks,
		&i.TotalSizeBytes,
		&i.Authors,
		&i.Series,
		&i.Libraries,
	)
	return i, err
}

const insertBook = `-- name: InsertBook :one
INSERT INTO books (library_id, library_key, title, series_id, series_number, language, annotation, publisher,
                   publisher_fold, year, rating, content_hash, added_at, imported_at, metadata_format)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id
`

type InsertBookParams struct {
	LibraryID      int64
	LibraryKey     string
	Title          string
	SeriesID       sql.NullInt64
	SeriesNumber   sql.NullFloat64
	Language       string
	Annotation     sql.NullString
	Publisher      sql.NullString
	PublisherFold  sql.NullString
	Year           sql.NullInt64
	Rating         sql.NullInt64
	ContentHash    string
	AddedAt        int64
	ImportedAt     int64
	MetadataFormat sql.NullString
}

func (q *Queries) InsertBook(ctx context.Context, arg InsertBookParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertBook,
		arg.LibraryID,
		arg.LibraryKey,
		arg.Title,
		arg.SeriesID,
		arg.SeriesNumber,
		arg.Language,
		arg.Annotation,
		arg.Publisher,
		arg.PublisherFold,
		arg.Year,
		arg.Rating,
		arg.ContentHash,
		arg.AddedAt,
		arg.ImportedAt,
		arg.MetadataFormat,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertBookFile = `-- name: InsertBookFile :one
INSERT INTO book_files (book_id, file_format, file_size, source_path, pages, mtime)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id
`

type InsertBookFileParams struct {
	BookID     int64
	FileFormat string
	FileSize   int64
	SourcePath string
	Pages      sql.NullInt64
	Mtime      int64
}

func (q *Queries) InsertBookFile(ctx context.Context, arg InsertBookFileParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertBookFile,
		arg.BookID,
		arg.FileFormat,
		arg.FileSize,
		arg.SourcePath,
		arg.Pages,
		arg.Mtime,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listBookFilesByLibrary = `-- name: ListBookFilesByLibrary :many
SELECT bf.id, bf.book_id, bf.source_path, bf.file_size, bf.mtime
FROM book_files bf
         JOIN books b ON b.id = bf.book_id
WHERE b.library_id = ?
`

type ListBookFilesByLibraryRow struct {
	ID         int64
	BookID     int64
	SourcePath string
	FileSize   int64
	Mtime      int64
}

func (q *Queries) ListBookFilesByLibrary(ctx context.Context, libraryID int64) ([]ListBookFilesByLibraryRow, error) {
	rows, err := q.db.QueryContext(ctx, listBookFilesByLibrary, libraryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBookFilesByLibraryRow
	for rows.Next() {
		var i ListBookFilesByLibraryRow
		if err := rows.Scan(
			&i.ID,
			&i.BookID,
			&i.SourcePath,
			&i.FileSize,
			&i.Mtime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBookIDsByLibrary = `-- name: ListBookIDsByLibrary :many
SELECT id
FROM books
WHERE library_id = ?
`

func (q *Queries) ListBookIDsByLibrary(ctx context.Context, libraryID int64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listBookIDsByLibrary, libraryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBooks = `-- name: ListBooks :many
SELECT id, library_id, library_key, title, series_id, series_number, language, annotation, metadata_checked, enrichment_checked, publisher, publisher_fold, year, rating, content_hash, metadata_format, added_at, imported_at, manually_matched, cover_prio
FROM books
ORDER BY added_at DESC, id DESC
LIMIT ? OFFSET ?
`

type ListBooksParams struct {
	Limit  int64
	Offset int64
}

// ListBooks is a plain paginated listing. Production serves the books grid via
// the dynamic Bob builder (db.FilterBooks); this static form currently backs
// test helpers. Kept deliberately, not orphaned.
func (q *Queries) ListBooks(ctx context.Context, arg ListBooksParams) ([]Book, error) {
	rows, err := q.db.QueryContext(ctx, listBooks, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Book
	for rows.Next() {
		var i Book
		if err := rows.Scan(
			&i.ID,
			&i.LibraryID,
			&i.LibraryKey,
			&i.Title,
			&i.SeriesID,
			&i.SeriesNumber,
			&i.Language,
			&i.Annotation,
			&i.MetadataChecked,
			&i.EnrichmentChecked,
			&i.Publisher,
			&i.PublisherFold,
			&i.Year,
			&i.Rating,
			&i.ContentHash,
			&i.MetadataFormat,
			&i.AddedAt,
			&i.ImportedAt,
			&i.ManuallyMatched,
			&i.CoverPrio,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDistinctFormats = `-- name: ListDistinctFormats :many
SELECT DISTINCT bf.file_format
FROM book_files bf
WHERE CAST(?1 AS INTEGER) = 0
   OR EXISTS (SELECT 1 FROM books b WHERE b.id = bf.book_id AND b.library_id = ?1)
ORDER BY bf.file_format
`

func (q *Queries) ListDistinctFormats(ctx context.Context, libraryID int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listDistinctFormats, libraryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var file_format string
		if err := rows.Scan(&file_format); err != nil {
			return nil, err
		}
		items = append(items, file_format)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDistinctLanguages = `-- name: ListDistinctLanguages :many
SELECT DISTINCT b.language
FROM books b
WHERE (CAST(?1 AS INTEGER) = 0 OR b.library_id = ?1)
ORDER BY b.language
`

func (q *Queries) ListDistinctLanguages(ctx context.Context, libraryID int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listDistinctLanguages, libraryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var language string
		if err := rows.Scan(&language); err != nil {
			return nil, err
		}
		items = append(items, language)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmptyBooksByLibrary = `-- name: ListEmptyBooksByLibrary :many
SELECT b.id
FROM books b
WHERE b.library_id = ?
  AND NOT EXISTS (SELECT 1 FROM book_files bf WHERE bf.book_id = b.id)
`

// ListEmptyBooksByLibrary finds books left with no files after pruning, in one
// pass; prune previously ran ListFilesForBook per book, O(books) statements
// per sync.
func (q *Queries) ListEmptyBooksByLibrary(ctx context.Context, libraryID int64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listEmptyBooksByLibrary, libraryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFilesForBook = `-- name: ListFilesForBook :many
SELECT id, book_id, file_format, file_size, source_path, pages, mtime
FROM book_files
WHERE book_id = ?
ORDER BY file_format
`

func (q *Queries) ListFilesForBook(ctx context.Context, bookID int64) ([]BookFile, error) {
	rows, err := q.db.QueryContext(ctx, listFilesForBook, bookID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BookFile
	for rows.Next() {
		var i BookFile
		if err := rows.Scan(
			&i.ID,
			&i.BookID,
			&i.FileFormat,
			&i.FileSize,
			&i.SourcePath,
			&i.Pages,
			&i.Mtime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFilesForBooks = `-- name: ListFilesForBooks :many
SELECT id, book_id, file_format, file_size, source_path, pages, mtime
FROM book_files
WHERE book_id IN (/*SLICE:book_ids*/?)
ORDER BY book_id, file_format
`

// ListFilesForBooks is the page-batched form of ListFilesForBook: one statement
// per page of books instead of one per book.
func (q *Queries) ListFilesForBooks(ctx context.Context, bookIds []int64) ([]BookFile, error) {
	query := listFilesForBooks
	var queryParams []interface{}
	if len(bookIds) > 0 {
		for _, v := range bookIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:book_ids*/?", strings.Repeat(",?", len(bookIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:book_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BookFile
	for rows.Next() {
		var i BookFile
		if err := rows.Scan(
			&i.ID,
			&i.BookID,
			&i.FileFormat,
			&i.FileSize,
			&i.SourcePath,
			&i.Pages,
			&i.Mtime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishersByLetter = `-- name: ListPublishersByLetter :many
SELECT COALESCE(publisher, '') AS name, COUNT(*) AS book_count
FROM books
WHERE publisher_fold IS NOT NULL
  AND publisher_fold != ''
  AND publisher_fold >= CAST(?1 AS TEXT)
  AND publisher_fold < CAST(?2 AS TEXT)
  AND (CAST(?3 AS INTEGER) = 0 OR library_id = ?3)
GROUP BY publisher
ORDER BY publisher_fold, publisher
LIMIT ?5 OFFSET ?4
`

type ListPublishersByLetterParams struct {
	Lo        string
	Hi        string
	LibraryID int64
	Off       int64
	Lim       int64
}

type ListPublishersByLetterRow struct {
	Name      string
	BookCount int64
}

// ListPublishersByLetter lists one alphabet bucket, paginated, range-seeking
// idx_books_publisher_fold (matching the @lo/@hi the caller computes from the
// folded letter) but GROUPing BY the raw publisher, so case variants ("Penguin"
// vs "PENGUIN") stay distinct entries that each match the exact-publisher book
// filter, while both still appear under the same letter.
func (q *Queries) ListPublishersByLetter(ctx context.Context, arg ListPublishersByLetterParams) ([]ListPublishersByLetterRow, error) {
	rows, err := q.db.QueryContext(ctx, listPublishersByLetter,
		arg.Lo,
		arg.Hi,
		arg.LibraryID,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublishersByLetterRow
	for rows.Next() {
		var i ListPublishersByLetterRow
		if err := rows.Scan(&i.Name, &i.BookCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishersNonLetter = `-- name: ListPublishersNonLetter :many
SELECT COALESCE(publisher, '') AS name, COUNT(*) AS book_count
FROM books
WHERE publisher_fold IS NOT NULL
  AND publisher_fold != ''
  AND NOT ((publisher_fold >= char(1040) AND publisher_fold < char(1072)) OR
           (publisher_fold >= char(65) AND publisher_fold < char(91)))
  AND (CAST(?1 AS INTEGER) = 0 OR library_id = ?1)
GROUP BY publisher
ORDER BY publisher_fold, publisher
LIMIT ?3 OFFSET ?2
`

type ListPublishersNonLetterParams struct {
	LibraryID int64
	Off       int64
	Lim       int64
}

type ListPublishersNonLetterRow struct {
	Name      string
	BookCount int64
}

// ListPublishersNonLetter is the '#' bucket (see ListAuthorsNonLetter).
func (q *Queries) ListPublishersNonLetter(ctx context.Context, arg ListPublishersNonLetterParams) ([]ListPublishersNonLetterRow, error) {
	rows, err := q.db.QueryContext(ctx, listPublishersNonLetter, arg.LibraryID, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublishersNonLetterRow
	for rows.Next() {
		var i ListPublishersNonLetterRow
		if err := rows.Scan(&i.Name, &i.BookCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markEnrichmentChecked = `-- name: MarkEnrichmentChecked :exec
UPDATE books
SET enrichment_checked = 1
WHERE id = ?
`

// MarkEnrichmentChecked records that online enrichment was attempted (even on a
// no-match), so the API isn't re-queried on every view.
func (q *Queries) MarkEnrichmentChecked(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, markEnrichmentChecked, id)
	return err
}

const markManuallyMatched = `-- name: MarkManuallyMatched :exec
UPDATE books
SET manually_matched   = 1,
    enrichment_checked = 1
WHERE id = ?
`

// MarkManuallyMatched flags a book as user-corrected (Fix Match) so the sync
// merge gap-fills but never overwrites it, and records enrichment as attempted.
// Used on the Fix-Match path even when the chosen volume changed nothing
// displayable, so the lock is durable regardless of the field diff.
func (q *Queries) MarkManuallyMatched(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, markManuallyMatched, id)
	return err
}

const markMetadataChecked = `-- name: MarkMetadataChecked :exec
UPDATE books
SET metadata_checked = 1
WHERE id = ?
`

// MarkMetadataChecked records that the lazy local backfill ran (and found
// nothing, or skipped the source, e.g. a PDF), so it isn't re-attempted.
func (q *Queries) MarkMetadataChecked(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, markMetadataChecked, id)
	return err
}

const publisherFirstChars = `-- name: PublisherFirstChars :many
SELECT DISTINCT substr(publisher_fold, 1, 1) AS first_char
FROM books
WHERE publisher_fold IS NOT NULL
  AND publisher_fold != ''
  AND (CAST(?1 AS INTEGER) = 0 OR library_id = ?1)
`

// PublisherFirstChars feeds the browse alphabet selector (see AuthorFirstChars).
// publisher_fold is the app-maintained uppercase Unicode fold (db.FoldNull), so
// a lowercase "penguin" lands under 'P' like the name_fold facets, not in '#',
// and idx_books_publisher_fold supplies the values without scanning publishers.
func (q *Queries) PublisherFirstChars(ctx context.Context, libraryID int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, publisherFirstChars, libraryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var first_char string
		if err := rows.Scan(&first_char); err != nil {
			return nil, err
		}
		items = append(items, first_char)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBook = `-- name: UpdateBook :exec
UPDATE books
SET title           = ?,
    series_id       = ?,
    series_number   = ?,
    language        = ?,
    annotation      = ?,
    publisher       = ?,
    publisher_fold  = ?,
    year            = ?,
    rating          = ?,
    content_hash    = ?,
    metadata_format = ?
WHERE id = ?
`

type UpdateBookParams struct {
	Title          string
	SeriesID       sql.NullInt64
	SeriesNumber   sql.NullFloat64
	Language       string
	Annotation     sql.NullString
	Publisher      sql.NullString
	PublisherFold  sql.NullString
	Year           sql.NullInt64
	Rating         sql.NullInt64
	ContentHash    string
	MetadataFormat sql.NullString
	ID             int64
}

func (q *Queries) UpdateBook(ctx context.Context, arg UpdateBookParams) error {
	_, err := q.db.ExecContext(ctx, updateBook,
		arg.Title,
		arg.SeriesID,
		arg.SeriesNumber,
		arg.Language,
		arg.Annotation,
		arg.Publisher,
		arg.PublisherFold,
		arg.Year,
		arg.Rating,
		arg.ContentHash,
		arg.MetadataFormat,
		arg.ID,
	)
	return err
}

const updateBookAnnotation = `-- name: UpdateBookAnnotation :exec
UPDATE books
SET annotation       = ?,
    metadata_checked = 1
WHERE id = ?
`

type UpdateBookAnnotationParams struct {
	Annotation sql.NullString
	ID         int64
}

// UpdateBookAnnotation records a lazily-backfilled annotation and marks the book
// as checked so the detail view never re-parses the source for it.
func (q *Queries) UpdateBookAnnotation(ctx context.Context, arg UpdateBookAnnotationParams) error {
	_, err := q.db.ExecContext(ctx, updateBookAnnotation, arg.Annotation, arg.ID)
	return err
}

const updateBookCoverPrio = `-- name: UpdateBookCoverPrio :exec
UPDATE books
SET cover_prio = ?
WHERE id = ?
`

type UpdateBookCoverPrioParams struct {
	CoverPrio int64
	ID        int64
}

// UpdateBookCoverPrio records the format priority of the cover the importer
// just cached, so later runs can refuse to downgrade it.
func (q *Queries) UpdateBookCoverPrio(ctx context.Context, arg UpdateBookCoverPrioParams) error {
	_, err := q.db.ExecContext(ctx, updateBookCoverPrio, arg.CoverPrio, arg.ID)
	return err
}

const updateBookEnrichment = `-- name: UpdateBookEnrichment :exec
UPDATE books
SET annotation         = ?,
    publisher          = ?,
    publisher_fold     = ?,
    year               = ?,
    content_hash       = ?,
    enrichment_checked = 1
WHERE id = ?
`

type UpdateBookEnrichmentParams struct {
	Annotation    sql.NullString
	Publisher     sql.NullString
	PublisherFold sql.NullString
	Year          sql.NullInt64
	ContentHash   string
	ID            int64
}

// UpdateBookEnrichment persists online-enrichment gap-fills (annotation,
// publisher, year), restamps content_hash so the cover cache-buster changes,
// and marks enrichment attempted.
func (q *Queries) UpdateBookEnrichment(ctx context.Context, arg UpdateBookEnrichmentParams) error {
	_, err := q.db.ExecContext(ctx, updateBookEnrichment,
		arg.Annotation,
		arg.Publisher,
		arg.PublisherFold,
		arg.Year,
		arg.ContentHash,
		arg.ID,
	)
	return err
}

const updateBookFile = `-- name: UpdateBookFile :exec
UPDATE book_files
SET file_size = ?,
    pages     = ?,
    mtime     = ?
WHERE id = ?
`

type UpdateBookFileParams struct {
	FileSize int64
	Pages    sql.NullInt64
	Mtime    int64
	ID       int64
}

func (q *Queries) UpdateBookFile(ctx context.Context, arg UpdateBookFileParams) error {
	_, err := q.db.ExecContext(ctx, updateBookFile,
		arg.FileSize,
		arg.Pages,
		arg.Mtime,
		arg.ID,
	)
	return err
}

const updateBookMatch = `-- name: UpdateBookMatch :exec
UPDATE books
SET title              = ?,
    series_id          = ?,
    series_number      = ?,
    annotation         = ?,
    publisher          = ?,
    publisher_fold     = ?,
    year               = ?,
    content_hash       = ?,
    enrichment_checked = 1,
    manually_matched   = 1
WHERE id = ?
`

type UpdateBookMatchParams struct {
	Title         string
	SeriesID      sql.NullInt64
	SeriesNumber  sql.NullFloat64
	Annotation    sql.NullString
	Publisher     sql.NullString
	PublisherFold sql.NullString
	Year          sql.NullInt64
	ContentHash   string
	ID            int64
}

// UpdateBookMatch overwrites a book's identity fields from a user-chosen volume
// (manual Fix Match): title and series in addition to the enrichment scalars,
// restamps content_hash, marks enrichment attempted, and sets manually_matched
// so the sync merge gap-fills but never overwrites this book again. Author/genre
// links are relinked separately.
func (q *Queries) UpdateBookMatch(ctx context.Context, arg UpdateBookMatchParams) error {
	_, err := q.db.ExecContext(ctx, updateBookMatch,
		arg.Title,
		arg.SeriesID,
		arg.SeriesNumber,
		arg.Annotation,
		arg.Publisher,
		arg.PublisherFold,
		arg.Year,
		arg.ContentHash,
		arg.ID,
	)
	return err
}
