// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: fts.sql

package dbq

import (
	"context"
)

const insertBookFTS = `-- name: InsertBookFTS :exec
INSERT INTO books_fts (book_id, title, authors, series, annotation)
VALUES (?, ?, ?, ?, ?)
`

type InsertBookFTSParams struct {
	BookID     string
	Title      string
	Authors    string
	Series     string
	Annotation string
}

func (q *Queries) InsertBookFTS(ctx context.Context, arg InsertBookFTSParams) error {
	_, err := q.db.ExecContext(ctx, insertBookFTS,
		arg.BookID,
		arg.Title,
		arg.Authors,
		arg.Series,
		arg.Annotation,
	)
	return err
}

const updateBookFTSAnnotation = `-- name: UpdateBookFTSAnnotation :exec
UPDATE books_fts
SET annotation = ?
WHERE book_id = ?
`

type UpdateBookFTSAnnotationParams struct {
	Annotation string
	BookID     string
}

func (q *Queries) UpdateBookFTSAnnotation(ctx context.Context, arg UpdateBookFTSAnnotationParams) error {
	_, err := q.db.ExecContext(ctx, updateBookFTSAnnotation, arg.Annotation, arg.BookID)
	return err
}

const updateBookFTSAuthors = `-- name: UpdateBookFTSAuthors :exec
UPDATE books_fts
SET authors = ?
WHERE book_id = ?
`

type UpdateBookFTSAuthorsParams struct {
	Authors string
	BookID  string
}

func (q *Queries) UpdateBookFTSAuthors(ctx context.Context, arg UpdateBookFTSAuthorsParams) error {
	_, err := q.db.ExecContext(ctx, updateBookFTSAuthors, arg.Authors, arg.BookID)
	return err
}

const updateBookFTSSeries = `-- name: UpdateBookFTSSeries :exec
UPDATE books_fts
SET series = ?
WHERE book_id = ?
`

type UpdateBookFTSSeriesParams struct {
	Series string
	BookID string
}

func (q *Queries) UpdateBookFTSSeries(ctx context.Context, arg UpdateBookFTSSeriesParams) error {
	_, err := q.db.ExecContext(ctx, updateBookFTSSeries, arg.Series, arg.BookID)
	return err
}

const updateBookFTSTitle = `-- name: UpdateBookFTSTitle :exec
UPDATE books_fts
SET title = ?
WHERE book_id = ?
`

type UpdateBookFTSTitleParams struct {
	Title  string
	BookID string
}

func (q *Queries) UpdateBookFTSTitle(ctx context.Context, arg UpdateBookFTSTitleParams) error {
	_, err := q.db.ExecContext(ctx, updateBookFTSTitle, arg.Title, arg.BookID)
	return err
}
