// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: genres.sql

package dbq

import (
	"context"
	"strings"
)

const countBookGenres = `-- name: CountBookGenres :one
SELECT COUNT(*)
FROM book_genres
WHERE book_id = ?
`

// CountBookGenres reports how many genres a book has. The online enrichment tier
// only gap-fills genres for a book that has none, so it never clobbers existing ones.
func (q *Queries) CountBookGenres(ctx context.Context, bookID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countBookGenres, bookID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteBookGenres = `-- name: DeleteBookGenres :exec
DELETE
FROM book_genres
WHERE book_id = ?
`

func (q *Queries) DeleteBookGenres(ctx context.Context, bookID int64) error {
	_, err := q.db.ExecContext(ctx, deleteBookGenres, bookID)
	return err
}

const genreFirstChars = `-- name: GenreFirstChars :many
SELECT DISTINCT substr(g.name_fold, 1, 1) AS first_char
FROM genres g
WHERE EXISTS (SELECT 1
              FROM book_genres bg
                       JOIN books b ON b.id = bg.book_id
              WHERE bg.genre_id = g.id
                AND (CAST(?1 AS INTEGER) = 0 OR b.library_id = ?1))
`

// GenreFirstChars feeds the browse alphabet selector (see AuthorFirstChars).
func (q *Queries) GenreFirstChars(ctx context.Context, libraryID int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, genreFirstChars, libraryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var first_char string
		if err := rows.Scan(&first_char); err != nil {
			return nil, err
		}
		items = append(items, first_char)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertBookGenre = `-- name: InsertBookGenre :exec
INSERT INTO book_genres (book_id, genre_id)
VALUES (?, ?)
ON CONFLICT DO NOTHING
`

type InsertBookGenreParams struct {
	BookID  int64
	GenreID int64
}

func (q *Queries) InsertBookGenre(ctx context.Context, arg InsertBookGenreParams) error {
	_, err := q.db.ExecContext(ctx, insertBookGenre, arg.BookID, arg.GenreID)
	return err
}

const insertGenre = `-- name: InsertGenre :one
INSERT INTO genres (name, name_fold)
VALUES (?, ?)
ON CONFLICT (name_fold) DO UPDATE SET name = name
RETURNING id
`

type InsertGenreParams struct {
	Name     string
	NameFold string
}

// InsertGenre upserts by name_fold; see InsertAuthor.
func (q *Queries) InsertGenre(ctx context.Context, arg InsertGenreParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertGenre, arg.Name, arg.NameFold)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listGenres = `-- name: ListGenres :many
SELECT g.id, g.name, g.name_fold, COUNT(bg.book_id) AS book_count
FROM genres g
         JOIN book_genres bg ON bg.genre_id = g.id
         JOIN books b ON b.id = bg.book_id
WHERE (CAST(?1 AS INTEGER) = 0 OR b.library_id = ?1)
GROUP BY g.id
ORDER BY g.name_fold
LIMIT ?3 OFFSET ?2
`

type ListGenresParams struct {
	LibraryID int64
	Off       int64
	Lim       int64
}

type ListGenresRow struct {
	ID        int64
	Name      string
	NameFold  string
	BookCount int64
}

// ListGenres lists every genre/tag (library-scoped), paginated, mirroring
// ListAuthors/ListSeries. Backs the OPDS genres index feed; page through it with
// @lim/@off.
func (q *Queries) ListGenres(ctx context.Context, arg ListGenresParams) ([]ListGenresRow, error) {
	rows, err := q.db.QueryContext(ctx, listGenres, arg.LibraryID, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGenresRow
	for rows.Next() {
		var i ListGenresRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.NameFold,
			&i.BookCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGenresByLetter = `-- name: ListGenresByLetter :many
SELECT g.name,
       (SELECT COUNT(*)
        FROM book_genres bg
        WHERE bg.genre_id = g.id
          AND (CAST(?1 AS INTEGER) = 0
            OR EXISTS (SELECT 1 FROM books b WHERE b.id = bg.book_id AND b.library_id = ?1))) AS book_count
FROM genres g
WHERE g.name_fold >= ?2
  AND g.name_fold < ?3
  AND EXISTS (SELECT 1
              FROM book_genres bg2
                       JOIN books b ON b.id = bg2.book_id
              WHERE bg2.genre_id = g.id
                AND (CAST(?1 AS INTEGER) = 0 OR b.library_id = ?1))
ORDER BY g.name_fold
LIMIT ?5 OFFSET ?4
`

type ListGenresByLetterParams struct {
	LibraryID int64
	Lo        string
	Hi        string
	Off       int64
	Lim       int64
}

type ListGenresByLetterRow struct {
	Name      string
	BookCount int64
}

// ListGenresByLetter lists one alphabet bucket, paginated, seeking genres.name_fold.
func (q *Queries) ListGenresByLetter(ctx context.Context, arg ListGenresByLetterParams) ([]ListGenresByLetterRow, error) {
	rows, err := q.db.QueryContext(ctx, listGenresByLetter,
		arg.LibraryID,
		arg.Lo,
		arg.Hi,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGenresByLetterRow
	for rows.Next() {
		var i ListGenresByLetterRow
		if err := rows.Scan(&i.Name, &i.BookCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGenresForBook = `-- name: ListGenresForBook :many
SELECT g.id, g.name, g.name_fold
FROM genres g
         JOIN book_genres bg ON bg.genre_id = g.id
WHERE bg.book_id = ?
ORDER BY g.name_fold
`

func (q *Queries) ListGenresForBook(ctx context.Context, bookID int64) ([]Genre, error) {
	rows, err := q.db.QueryContext(ctx, listGenresForBook, bookID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Genre
	for rows.Next() {
		var i Genre
		if err := rows.Scan(&i.ID, &i.Name, &i.NameFold); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGenresForBooks = `-- name: ListGenresForBooks :many
SELECT bg.book_id, g.id, g.name
FROM genres g
         JOIN book_genres bg ON bg.genre_id = g.id
WHERE bg.book_id IN (/*SLICE:book_ids*/?)
ORDER BY bg.book_id, g.name_fold
`

type ListGenresForBooksRow struct {
	BookID int64
	ID     int64
	Name   string
}

// ListGenresForBooks is the page-batched form of ListGenresForBook.
func (q *Queries) ListGenresForBooks(ctx context.Context, bookIds []int64) ([]ListGenresForBooksRow, error) {
	query := listGenresForBooks
	var queryParams []interface{}
	if len(bookIds) > 0 {
		for _, v := range bookIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:book_ids*/?", strings.Repeat(",?", len(bookIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:book_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGenresForBooksRow
	for rows.Next() {
		var i ListGenresForBooksRow
		if err := rows.Scan(&i.BookID, &i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGenresNonLetter = `-- name: ListGenresNonLetter :many
SELECT g.name,
       (SELECT COUNT(*)
        FROM book_genres bg
        WHERE bg.genre_id = g.id
          AND (CAST(?1 AS INTEGER) = 0
            OR EXISTS (SELECT 1 FROM books b WHERE b.id = bg.book_id AND b.library_id = ?1))) AS book_count
FROM genres g
WHERE NOT ((g.name_fold >= char(1040) AND g.name_fold < char(1072)) OR
           (g.name_fold >= char(65) AND g.name_fold < char(91)))
  AND EXISTS (SELECT 1
              FROM book_genres bg2
                       JOIN books b ON b.id = bg2.book_id
              WHERE bg2.genre_id = g.id
                AND (CAST(?1 AS INTEGER) = 0 OR b.library_id = ?1))
ORDER BY g.name_fold
LIMIT ?3 OFFSET ?2
`

type ListGenresNonLetterParams struct {
	LibraryID int64
	Off       int64
	Lim       int64
}

type ListGenresNonLetterRow struct {
	Name      string
	BookCount int64
}

// ListGenresNonLetter is the '#' bucket (see ListAuthorsNonLetter).
func (q *Queries) ListGenresNonLetter(ctx context.Context, arg ListGenresNonLetterParams) ([]ListGenresNonLetterRow, error) {
	rows, err := q.db.QueryContext(ctx, listGenresNonLetter, arg.LibraryID, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGenresNonLetterRow
	for rows.Next() {
		var i ListGenresNonLetterRow
		if err := rows.Scan(&i.Name, &i.BookCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
