// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identifiers.sql

package dbq

import (
	"context"
	"strings"
)

const countBookIdentifiers = `-- name: CountBookIdentifiers :one
SELECT COUNT(*)
FROM book_identifiers
WHERE book_id = ?
`

func (q *Queries) CountBookIdentifiers(ctx context.Context, bookID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countBookIdentifiers, bookID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertBookIdentifier = `-- name: InsertBookIdentifier :exec
INSERT INTO book_identifiers (book_id, type, value)
VALUES (?, ?, ?)
ON CONFLICT (book_id, type) DO UPDATE SET value = excluded.value
`

type InsertBookIdentifierParams struct {
	BookID int64
	Type   string
	Value  string
}

func (q *Queries) InsertBookIdentifier(ctx context.Context, arg InsertBookIdentifierParams) error {
	_, err := q.db.ExecContext(ctx, insertBookIdentifier, arg.BookID, arg.Type, arg.Value)
	return err
}

const insertBookIdentifierIfAbsent = `-- name: InsertBookIdentifierIfAbsent :exec
INSERT INTO book_identifiers (book_id, type, value)
VALUES (?, ?, ?)
ON CONFLICT (book_id, type) DO NOTHING
`

type InsertBookIdentifierIfAbsentParams struct {
	BookID int64
	Type   string
	Value  string
}

// InsertBookIdentifierIfAbsent is the gap-fill variant of InsertBookIdentifier:
// it never replaces an existing value, so a lower-priority edition cannot
// overwrite e.g. the EPUB's ISBN-13 with its own ISBN-10.
func (q *Queries) InsertBookIdentifierIfAbsent(ctx context.Context, arg InsertBookIdentifierIfAbsentParams) error {
	_, err := q.db.ExecContext(ctx, insertBookIdentifierIfAbsent, arg.BookID, arg.Type, arg.Value)
	return err
}

const listIdentifiersForBook = `-- name: ListIdentifiersForBook :many
SELECT type, value
FROM book_identifiers
WHERE book_id = ?
ORDER BY type
`

type ListIdentifiersForBookRow struct {
	Type  string
	Value string
}

func (q *Queries) ListIdentifiersForBook(ctx context.Context, bookID int64) ([]ListIdentifiersForBookRow, error) {
	rows, err := q.db.QueryContext(ctx, listIdentifiersForBook, bookID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIdentifiersForBookRow
	for rows.Next() {
		var i ListIdentifiersForBookRow
		if err := rows.Scan(&i.Type, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIdentifiersForBooks = `-- name: ListIdentifiersForBooks :many
SELECT book_id, type, value
FROM book_identifiers
WHERE book_id IN (/*SLICE:book_ids*/?)
ORDER BY book_id, type
`

// ListIdentifiersForBooks is the page-batched form of ListIdentifiersForBook.
func (q *Queries) ListIdentifiersForBooks(ctx context.Context, bookIds []int64) ([]BookIdentifier, error) {
	query := listIdentifiersForBooks
	var queryParams []interface{}
	if len(bookIds) > 0 {
		for _, v := range bookIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:book_ids*/?", strings.Repeat(",?", len(bookIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:book_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BookIdentifier
	for rows.Next() {
		var i BookIdentifier
		if err := rows.Scan(&i.BookID, &i.Type, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
