// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: libraries.sql

package dbq

import (
	"context"
	"database/sql"
)

const deleteLibrary = `-- name: DeleteLibrary :exec
DELETE
FROM libraries
WHERE id = ?
`

func (q *Queries) DeleteLibrary(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteLibrary, id)
	return err
}

const getLibrary = `-- name: GetLibrary :one
SELECT id, name, type, path, sync_interval_seconds, status, purge_at, last_sync_at, last_sync_error, checkpoint, created_at
FROM libraries
WHERE id = ?
`

func (q *Queries) GetLibrary(ctx context.Context, id int64) (Library, error) {
	row := q.db.QueryRowContext(ctx, getLibrary, id)
	var i Library
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Path,
		&i.SyncIntervalSeconds,
		&i.Status,
		&i.PurgeAt,
		&i.LastSyncAt,
		&i.LastSyncError,
		&i.Checkpoint,
		&i.CreatedAt,
	)
	return i, err
}

const insertLibrary = `-- name: InsertLibrary :one
INSERT INTO libraries (name, type, path, sync_interval_seconds, status, created_at)
VALUES (?, ?, ?, ?, 'active', ?)
RETURNING id
`

type InsertLibraryParams struct {
	Name                string
	Type                string
	Path                string
	SyncIntervalSeconds int64
	CreatedAt           int64
}

func (q *Queries) InsertLibrary(ctx context.Context, arg InsertLibraryParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertLibrary,
		arg.Name,
		arg.Type,
		arg.Path,
		arg.SyncIntervalSeconds,
		arg.CreatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listLibraries = `-- name: ListLibraries :many
SELECT id, name, type, path, sync_interval_seconds, status, purge_at, last_sync_at, last_sync_error, checkpoint, created_at
FROM libraries
ORDER BY created_at
`

func (q *Queries) ListLibraries(ctx context.Context) ([]Library, error) {
	rows, err := q.db.QueryContext(ctx, listLibraries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Library
	for rows.Next() {
		var i Library
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Path,
			&i.SyncIntervalSeconds,
			&i.Status,
			&i.PurgeAt,
			&i.LastSyncAt,
			&i.LastSyncError,
			&i.Checkpoint,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLibrariesWithBookCount = `-- name: ListLibrariesWithBookCount :many
SELECT s.id, s.name, s.type, s.path, s.sync_interval_seconds, s.status, s.purge_at, s.last_sync_at, s.last_sync_error, s.checkpoint, s.created_at, COUNT(b.id) AS book_count
FROM libraries s
         LEFT JOIN books b ON b.library_id = s.id
GROUP BY s.id
ORDER BY s.created_at
`

type ListLibrariesWithBookCountRow struct {
	ID                  int64
	Name                string
	Type                string
	Path                string
	SyncIntervalSeconds int64
	Status              string
	PurgeAt             sql.NullInt64
	LastSyncAt          sql.NullInt64
	LastSyncError       sql.NullString
	Checkpoint          sql.NullString
	CreatedAt           int64
	BookCount           int64
}

func (q *Queries) ListLibrariesWithBookCount(ctx context.Context) ([]ListLibrariesWithBookCountRow, error) {
	rows, err := q.db.QueryContext(ctx, listLibrariesWithBookCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLibrariesWithBookCountRow
	for rows.Next() {
		var i ListLibrariesWithBookCountRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Path,
			&i.SyncIntervalSeconds,
			&i.Status,
			&i.PurgeAt,
			&i.LastSyncAt,
			&i.LastSyncError,
			&i.Checkpoint,
			&i.CreatedAt,
			&i.BookCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingPurgeLibraries = `-- name: ListPendingPurgeLibraries :many
SELECT id, name, type, path, sync_interval_seconds, status, purge_at, last_sync_at, last_sync_error, checkpoint, created_at
FROM libraries
WHERE status = 'pending_purge'
  AND purge_at IS NOT NULL
  AND purge_at <= ?
`

func (q *Queries) ListPendingPurgeLibraries(ctx context.Context, purgeAt sql.NullInt64) ([]Library, error) {
	rows, err := q.db.QueryContext(ctx, listPendingPurgeLibraries, purgeAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Library
	for rows.Next() {
		var i Library
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Path,
			&i.SyncIntervalSeconds,
			&i.Status,
			&i.PurgeAt,
			&i.LastSyncAt,
			&i.LastSyncError,
			&i.Checkpoint,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLibrary = `-- name: UpdateLibrary :exec
UPDATE libraries
SET name                  = ?,
    path                  = ?,
    sync_interval_seconds = ?
WHERE id = ?
`

type UpdateLibraryParams struct {
	Name                string
	Path                string
	SyncIntervalSeconds int64
	ID                  int64
}

func (q *Queries) UpdateLibrary(ctx context.Context, arg UpdateLibraryParams) error {
	_, err := q.db.ExecContext(ctx, updateLibrary,
		arg.Name,
		arg.Path,
		arg.SyncIntervalSeconds,
		arg.ID,
	)
	return err
}

const updateLibraryCheckpoint = `-- name: UpdateLibraryCheckpoint :exec
UPDATE libraries
SET checkpoint = ?
WHERE id = ?
`

type UpdateLibraryCheckpointParams struct {
	Checkpoint sql.NullString
	ID         int64
}

func (q *Queries) UpdateLibraryCheckpoint(ctx context.Context, arg UpdateLibraryCheckpointParams) error {
	_, err := q.db.ExecContext(ctx, updateLibraryCheckpoint, arg.Checkpoint, arg.ID)
	return err
}

const updateLibraryLastSync = `-- name: UpdateLibraryLastSync :exec
UPDATE libraries
SET status          = 'active',
    last_sync_at    = ?,
    last_sync_error = NULL
WHERE id = ?
  AND status != 'pending_purge'
`

type UpdateLibraryLastSyncParams struct {
	LastSyncAt sql.NullInt64
	ID         int64
}

// UpdateLibraryLastSync stamps a successful (or skipped-unchanged) sync. It
// also resets status to 'active' so a library that previously failed recovers
// as soon as a later sync succeeds, instead of wearing the error badge forever.
// A library deleted mid-sync (status flipped to 'pending_purge' while the run
// was in flight) is excluded: resurrecting it to 'active' would silently cancel
// the purge while leaving purge_at set.
func (q *Queries) UpdateLibraryLastSync(ctx context.Context, arg UpdateLibraryLastSyncParams) error {
	_, err := q.db.ExecContext(ctx, updateLibraryLastSync, arg.LastSyncAt, arg.ID)
	return err
}

const updateLibraryStatus = `-- name: UpdateLibraryStatus :exec
UPDATE libraries
SET status          = ?,
    purge_at        = ?,
    last_sync_error = ?
WHERE id = ?
`

type UpdateLibraryStatusParams struct {
	Status        string
	PurgeAt       sql.NullInt64
	LastSyncError sql.NullString
	ID            int64
}

func (q *Queries) UpdateLibraryStatus(ctx context.Context, arg UpdateLibraryStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateLibraryStatus,
		arg.Status,
		arg.PurgeAt,
		arg.LastSyncError,
		arg.ID,
	)
	return err
}

const updateLibrarySyncError = `-- name: UpdateLibrarySyncError :exec
UPDATE libraries
SET status          = 'error',
    last_sync_error = ?
WHERE id = ?
`

type UpdateLibrarySyncErrorParams struct {
	LastSyncError sql.NullString
	ID            int64
}

func (q *Queries) UpdateLibrarySyncError(ctx context.Context, arg UpdateLibrarySyncErrorParams) error {
	_, err := q.db.ExecContext(ctx, updateLibrarySyncError, arg.LastSyncError, arg.ID)
	return err
}
