// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbq

import (
	"database/sql"
)

type Author struct {
	ID       int64
	Name     string
	NameFold string
}

type Book struct {
	ID                int64
	LibraryID         int64
	LibraryKey        string
	Title             string
	SeriesID          sql.NullInt64
	SeriesNumber      sql.NullFloat64
	Language          string
	Annotation        sql.NullString
	MetadataChecked   int64
	EnrichmentChecked int64
	Publisher         sql.NullString
	PublisherFold     sql.NullString
	Year              sql.NullInt64
	Rating            sql.NullInt64
	ContentHash       string
	MetadataFormat    sql.NullString
	AddedAt           int64
	ImportedAt        int64
	ManuallyMatched   int64
	CoverPrio         int64
	CoverState        int64
}

type BookAuthor struct {
	BookID   int64
	AuthorID int64
}

type BookFile struct {
	ID         int64
	BookID     int64
	FileFormat string
	FileSize   int64
	SourcePath string
	Pages      sql.NullInt64
	Mtime      int64
}

type BookGenre struct {
	BookID  int64
	GenreID int64
}

type BookIdentifier struct {
	BookID int64
	Type   string
	Value  string
}

type BooksFt struct {
	BookID     string
	Title      string
	Authors    string
	Series     string
	Annotation string
}

type Genre struct {
	ID       int64
	Name     string
	NameFold string
}

type Library struct {
	ID                  int64
	Name                string
	Type                string
	Path                string
	SyncIntervalSeconds int64
	Status              string
	PurgeAt             sql.NullInt64
	LastSyncAt          sql.NullInt64
	LastSyncError       sql.NullString
	Checkpoint          sql.NullString
	CreatedAt           int64
}

type Series struct {
	ID       int64
	Name     string
	NameFold string
}

type Setting struct {
	Key   string
	Value string
}
