// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: series.sql

package dbq

import (
	"context"
)

const getSeries = `-- name: GetSeries :one
SELECT id, name, name_fold
FROM series
WHERE id = ?
`

func (q *Queries) GetSeries(ctx context.Context, id int64) (Series, error) {
	row := q.db.QueryRowContext(ctx, getSeries, id)
	var i Series
	err := row.Scan(&i.ID, &i.Name, &i.NameFold)
	return i, err
}

const insertSeries = `-- name: InsertSeries :one
INSERT INTO series (name, name_fold)
VALUES (?, ?)
ON CONFLICT (name_fold) DO UPDATE SET name = name
RETURNING id
`

type InsertSeriesParams struct {
	Name     string
	NameFold string
}

// InsertSeries upserts by name_fold; see InsertAuthor.
func (q *Queries) InsertSeries(ctx context.Context, arg InsertSeriesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertSeries, arg.Name, arg.NameFold)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listSeries = `-- name: ListSeries :many
SELECT s.id, s.name, s.name_fold, COUNT(b.id) AS book_count
FROM series s
         JOIN books b ON b.series_id = s.id
WHERE (CAST(?1 AS INTEGER) = 0 OR b.library_id = ?1)
GROUP BY s.id
ORDER BY s.name_fold
LIMIT ?3 OFFSET ?2
`

type ListSeriesParams struct {
	LibraryID int64
	Off       int64
	Lim       int64
}

type ListSeriesRow struct {
	ID        int64
	Name      string
	NameFold  string
	BookCount int64
}

// ListSeries lists every series (library-scoped), paginated, mirroring
// ListAuthors for OPDS index feeds.
func (q *Queries) ListSeries(ctx context.Context, arg ListSeriesParams) ([]ListSeriesRow, error) {
	rows, err := q.db.QueryContext(ctx, listSeries, arg.LibraryID, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSeriesRow
	for rows.Next() {
		var i ListSeriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.NameFold,
			&i.BookCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSeriesByLetter = `-- name: ListSeriesByLetter :many
SELECT s.id,
       s.name,
       (SELECT COUNT(*)
        FROM books b
        WHERE b.series_id = s.id
          AND (CAST(?1 AS INTEGER) = 0 OR b.library_id = ?1)) AS book_count
FROM series s
WHERE s.name_fold >= ?2
  AND s.name_fold < ?3
  AND EXISTS (SELECT 1
              FROM books b
              WHERE b.series_id = s.id
                AND (CAST(?1 AS INTEGER) = 0 OR b.library_id = ?1))
ORDER BY s.name_fold
LIMIT ?5 OFFSET ?4
`

type ListSeriesByLetterParams struct {
	LibraryID int64
	Lo        string
	Hi        string
	Off       int64
	Lim       int64
}

type ListSeriesByLetterRow struct {
	ID        int64
	Name      string
	BookCount int64
}

// ListSeriesByLetter lists one alphabet bucket, paginated, seeking series.name_fold.
func (q *Queries) ListSeriesByLetter(ctx context.Context, arg ListSeriesByLetterParams) ([]ListSeriesByLetterRow, error) {
	rows, err := q.db.QueryContext(ctx, listSeriesByLetter,
		arg.LibraryID,
		arg.Lo,
		arg.Hi,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSeriesByLetterRow
	for rows.Next() {
		var i ListSeriesByLetterRow
		if err := rows.Scan(&i.ID, &i.Name, &i.BookCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSeriesNonLetter = `-- name: ListSeriesNonLetter :many
SELECT s.id,
       s.name,
       (SELECT COUNT(*)
        FROM books b
        WHERE b.series_id = s.id
          AND (CAST(?1 AS INTEGER) = 0 OR b.library_id = ?1)) AS book_count
FROM series s
WHERE NOT ((s.name_fold >= char(1040) AND s.name_fold < char(1072)) OR
           (s.name_fold >= char(65) AND s.name_fold < char(91)))
  AND EXISTS (SELECT 1
              FROM books b
              WHERE b.series_id = s.id
                AND (CAST(?1 AS INTEGER) = 0 OR b.library_id = ?1))
ORDER BY s.name_fold
LIMIT ?3 OFFSET ?2
`

type ListSeriesNonLetterParams struct {
	LibraryID int64
	Off       int64
	Lim       int64
}

type ListSeriesNonLetterRow struct {
	ID        int64
	Name      string
	BookCount int64
}

// ListSeriesNonLetter is the '#' bucket (see ListAuthorsNonLetter).
// char() bounds mirror cyrLo/cyrHi/latLo/latHi in internal/api/letters.go;
// drift guard: internal/api/letters_bounds_test.go TestSQLBucketBoundsMatchGoConstants
func (q *Queries) ListSeriesNonLetter(ctx context.Context, arg ListSeriesNonLetterParams) ([]ListSeriesNonLetterRow, error) {
	rows, err := q.db.QueryContext(ctx, listSeriesNonLetter, arg.LibraryID, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSeriesNonLetterRow
	for rows.Next() {
		var i ListSeriesNonLetterRow
		if err := rows.Scan(&i.ID, &i.Name, &i.BookCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const seriesFirstChars = `-- name: SeriesFirstChars :many
SELECT DISTINCT substr(s.name_fold, 1, 1) AS first_char
FROM series s
WHERE EXISTS (SELECT 1
              FROM books b
              WHERE b.series_id = s.id
                AND (CAST(?1 AS INTEGER) = 0 OR b.library_id = ?1))
`

// SeriesFirstChars feeds the browse alphabet selector (see AuthorFirstChars).
func (q *Queries) SeriesFirstChars(ctx context.Context, libraryID int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, seriesFirstChars, libraryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var first_char string
		if err := rows.Scan(&first_char); err != nil {
			return nil, err
		}
		items = append(items, first_char)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
