repos:
- repo: https://github.com/compilerla/conventional-pre-commit
  rev: v4.4.0
  hooks:
    - id: conventional-pre-commit
      stages:
        - commit-msg

- repo: local
  hooks:
    - id: linters
      name: Run linters
      types_or: [go, javascript, jsx, ts, tsx, vue, html]
      pass_filenames: false
      language: system
      entry: task lint
      stages:
        - pre-commit

    - id: tests
      name: Run tests
      types_or: [go, javascript, jsx, ts, tsx, vue, html]
      pass_filenames: false
      language: system
      entry: task test
      stages:
        - pre-commit
